In [1]:
from database.sqlite_manager import SQLiteManager
from services.excel_services import ExcelService

In [2]:
db = SQLiteManager()

db.initialize_database()

Database initialized successfully

In [3]:
excel_service = ExcelService(
    "D114441.xlsx"
)

holdings_df = excel_service.load_holdings()

holdings_df.head()

,Scrip/Contract,Company Name,ISIN,MarketCap,Sector,Quantity,Blocked_qty,Avg Trading Price,Prev closing Price,Invested Value,Market Value as of last trading day,Overall Gain/Loss,Realised Gain/Loss,Holding Weightage,ARQ Prime Quantity
0,SANDUMA,Sandur Manganese,INE149K01016,SmallCap,Mining & Minerals,25,0,252.60,190.35,6314,4759,-1556.25,0,1.69,0
1,TCS,TCS,INE467B01029,LargeCap,IT - Software,7,0,4110.89,2200.80,28776,15406,-13370.63,0,5.46,0
2,ENERGY,ENERGY,INF769K01PR2,NaN,NaN,250,0,39.59,38.30,9898,9575,-322.50,0,3.40,0
3,APLAPOLLO,APL Apollo Tubes,INE702C01027,MidCap,Steel/Sponge Iron/Pig Iron,5,0,2130.01,2153.50,10650,10768,117.45,0,3.82,0
4,IREDA,IREDA,INE202E01016,SmallCap,Finance/NBFC,118,0,201.41,111.71,23766,13182,-10584.60,0,4.68,0

In [4]:
conn = db.get_connection()

excel_service.save_to_database(
    holdings_df,
    conn
)

conn.close()

19 holdings inserted

In [5]:
import pandas as pd

conn = db.get_connection()

df = pd.read_sql(
    """
    SELECT *
    FROM holdings
    """,
    conn
)

df.head()

,symbol,company_name,isin,market_cap,sector,quantity,avg_trading_price,invested_value,market_value,overall_gain_loss,holding_weightage
0,SANDUMA,Sandur Manganese,INE149K01016,SmallCap,Mining & Minerals,25,252.60,6314,4759,-1556.25,1.69
1,TCS,TCS,INE467B01029,LargeCap,IT - Software,7,4110.89,28776,15406,-13370.63,5.46
2,ENERGY,ENERGY,INF769K01PR2,NaN,NaN,250,39.59,9898,9575,-322.50,3.40
3,APLAPOLLO,APL Apollo Tubes,INE702C01027,MidCap,Steel/Sponge Iron/Pig Iron,5,2130.01,10650,10768,117.45,3.82
4,IREDA,IREDA,INE202E01016,SmallCap,Finance/NBFC,118,201.41,23766,13182,-10584.60,4.68

In [6]:
pd.read_sql(
    """
    SELECT
        symbol,
        market_value
    FROM holdings
    ORDER BY market_value DESC
    LIMIT 5
    """,
    conn
)

       symbol  market_value
0  BHARATFORG         33063
1  MANAPPURAM         28294
2         SBC         26147
3  ANANDRATHI         22110
4         ABB         21822