In [1]:
from agents.sql_agent import SQLAgent
from services.query_service import QueryService

In [2]:
agent = SQLAgent()

query_service = QueryService(
    "data/portfolio.db"
)

In [6]:
question = """
What is my largest holding?
"""

In [7]:
sql_query = agent.generate_sql(
    question
)

print(sql_query)

SELECT * FROM holdings ORDER BY market_value DESC LIMIT 1;

In [8]:
result = query_service.execute_query(
    sql_query
)

result

,symbol,company_name,isin,market_cap,sector,quantity,avg_trading_price,invested_value,market_value,overall_gain_loss,holding_weightage
0,BHARATFORG,Bharat Forge,INE465A01025,MidCap,Castings/Forgings,17,1421.59,24167,33063,8896.27,11.73

In [9]:
def ask_portfolio(question):

    sql_query = (
        agent.generate_sql(question)
    )

    result = (
        query_service.execute_query(
            sql_query
        )
    )

    return result

In [10]:
ask_portfolio(
    "Which stock has highest profit?"
)

  symbol company_name  overall_gain_loss
0    SBC  SBC Exports            10224.9

In [1]:
from agents.sql_orchestrator import (
    SQLOrchestrator
)

orchestrator = SQLOrchestrator(
    "data/portfolio.db"
)

In [2]:
response = orchestrator.ask(
    "What are my top 5 holdings?"
)

In [6]:
response = orchestrator.ask(
    "Who is the prime minister of India?"
)

In [7]:
response["sql"]

KeyError: 'sql'

In [8]:
response["result"]

KeyError: 'result'

In [9]:
response

{'status': 'rejected', 'message': 'Please ask portfolio related questions.'}